<?xml version="1.0"?>
<!DOCTYPE issues [
<!ELEMENT issues (issue*)>
<!ATTLIST issues burpVersion CDATA "">
<!ATTLIST issues exportTime CDATA "">
<!ELEMENT issue (serialNumber, type, name, host, path, location, severity, confidence, issueBackground?, remediationBackground?, issueDetail?, issueDetailItems?, remediationDetail?, requestresponse*)>
<!ELEMENT serialNumber (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT host (#PCDATA)>
<!ATTLIST host ip CDATA "">
<!ELEMENT path (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT severity (#PCDATA)>
<!ELEMENT confidence (#PCDATA)>
<!ELEMENT issueBackground (#PCDATA)>
<!ELEMENT remediationBackground (#PCDATA)>
<!ELEMENT issueDetail (#PCDATA)>
<!ELEMENT issueDetailItems (issueDetailItem*)>
<!ELEMENT issueDetailItem (#PCDATA)>
<!ELEMENT remediationDetail (#PCDATA)>
<!ELEMENT requestresponse (request?, response?, responseRedirected?)>
<!ELEMENT request (#PCDATA)>
<!ATTLIST request method CDATA "">
<!ATTLIST request base64 (true|false) "false">
<!ELEMENT response (#PCDATA)>
<!ATTLIST response base64 (true|false) "false">
<!ELEMENT responseRedirected (#PCDATA)>
]>
<issues burpVersion="1.6.05" exportTime="Thu Oct 16 14:28:51 EDT 2014">
  <issue>
    <serialNumber>2631399502080171008</serialNumber>
    <type>2097952</type>
    <name>JavaScript injection (DOM-based)</name>
    <host ip="192.168.216.139">http://192.168.216.139:8080</host>
    <path><![CDATA[/WebGoat/javascript/menu_system.js]]></path>
    <location><![CDATA[/WebGoat/javascript/menu_system.js]]></location>
    <severity>High</severity>
    <confidence>Firm</confidence>
    <issueBackground><![CDATA[DOM-based JavaScript injection vulnerabilities arise when a client-side script within an application's response reads data from a controllable part of the DOM (for example, the URL), and executes this data as JavaScript. An attacker may be able to use the vulnerability to construct a URL which, if visited by another application user, will cause JavaScript code supplied by the attacker to execute within the user's browser in the context of that user's session with the application.<br><br>The attacker-supplied code can perform a wide variety of actions, such as stealing the victim's session token or login credentials, performing arbitrary actions on the victim's behalf, and logging their keystrokes.<br><br>Users can be induced to visit the attacker's crafted URL in various ways, similar to the usual attack delivery vectors for reflected cross-site scripting vulnerabilities. ]]></issueBackground>
    <remediationBackground><![CDATA[Static analysis of code to identify vulnerabilities of this kind may lead to false positives that are not actually exploitable. You should review the highlighted code and related execution paths to determine whether the application is indeed vulnerable, or whether mitigations are in place that would prevent exploitation.<br><br>The most effective way to avoid DOM-based JavaScript injection vulnerabilities is not to execute as JavaScript any data that originated from an untrusted source. If the desired functionality of the application means that this behavior is unavoidable, then defenses must be implemented within the client-side code to prevent malicious data from executing as script. In many cases, the relevant data can be validated on a whitelist basis, to allow only content that is known to be safe. In other cases, it will be necessary to sanitize or encode the data. This can be a complex task, and may need to involve a combination of JavaScript escaping and HTML encoding, in the appropriate sequence.]]></remediationBackground>
    <issueDetail><![CDATA[The application may be vulnerable to DOM-based JavaScript injection. Data is read from <b>document.URL</b> and written to <b>eval()</b> via the following statements:<ul><li>ur=document.URL;</li><li>pr=ur.substring(x+1,ur.length).split("&amp;");</li><li>nv=pr[i].split("=");</li><li>mn="menu"+unescape(nv[1]);</li><li>eval("trigMenuMagic1('"+mn+"',"+opt+")");</li></ul>]]></issueDetail>
    <requestresponse>
      <request method="GET" base64="true"><![CDATA[R0VUIC9XZWJHb2F0L2phdmFzY3JpcHQvbWVudV9zeXN0ZW0uanMgSFRUUC8xLjENCkFjY2VwdDogYXBwbGljYXRpb24vamF2YXNjcmlwdCwgKi8qO3E9MC44DQpSZWZlcmVyOiBodHRwOi8vMTkyLjE2OC4yMTYuMTM5OjgwODAvV2ViR29hdC9hdHRhY2sNCkFjY2VwdC1MYW5ndWFnZTogZW4tVVMNClVzZXItQWdlbnQ6IE1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDYuMzsgV09XNjQ7IFRyaWRlbnQvNy4wOyBydjoxMS4wKSBsaWtlIEdlY2tvDQpBY2NlcHQtRW5jb2Rpbmc6IGd6aXAsIGRlZmxhdGUNClByb3h5LUNvbm5lY3Rpb246IEtlZXAtQWxpdmUNCkROVDogMQ0KSG9zdDogMTkyLjE2OC4yMTYuMTM5OjgwODANCkNvb2tpZTogSlNFU1NJT05JRD1GOUQzODc1RkREQzgyRDU2QkU3OUU5MkJCMEFCNDMyMQ0KQXV0aG9yaXphdGlvbjogQmFzaWMgWjNWbGMzUTZaM1ZsYzNRPQ0KDQo=]]></request>
      <response base64="true"><![CDATA[SFRUUC8xLjEgMjAwIE9LDQpTZXJ2ZXI6IEFwYWNoZS1Db3lvdGUvMS4xDQpQcmFnbWE6IE5vLWNhY2hlDQpDYWNoZS1Db250cm9sOiBuby1jYWNoZQ0KRXhwaXJlczogV2VkLCAzMSBEZWMgMTk2OSAxOTowMDowMCBFU1QNCkFjY2VwdC1SYW5nZXM6IGJ5dGVzDQpFVGFnOiBXLyI3NjY4LTEzNzQwMDMxOTgwMDAiDQpMYXN0LU1vZGlmaWVkOiBUdWUsIDE2IEp1bCAyMDEzIDE5OjMzOjE4IEdNVA0KQ29udGVudC1UeXBlOiB0ZXh0L2phdmFzY3JpcHQNCkNvbnRlbnQtTGVuZ3RoOiA3NjY4DQpEYXRlOiBUaHUsIDE2IE9jdCAyMDE0IDE4OjA4OjMwIEdNVA0KDQpmdW5jdGlvbiBjaGFuZ2VMYW5ndWFnZSgpew0KCXZhciBzZWxlY3Q9TU1fZmluZE9iaigibGFuZ3VhZ2UiLG51bGwpOw0KCQ0KCWRvY3VtZW50LmxvY2F0aW9uPSJhdHRhY2s/bGFuZ3VhZ2U9IitzZWxlY3QudmFsdWU7DQp9CQ0KDQoNCmZ1bmN0aW9uIE1NX2ZpbmRPYmoobiwgZCkgew0KICB2YXIgcCxpLHg7ICBpZighZCkgZD1kb2N1bWVudDsgaWYoKHA9bi5pbmRleE9mKCI/IikpPjAmJnBhcmVudC5mcmFtZXMubGVuZ3RoKSB7DQogICAgZD1wYXJlbnQuZnJhbWVzW24uc3Vic3RyaW5nKHArMSldLmRvY3VtZW50OyBuPW4uc3Vic3RyaW5nKDAscCk7fQ0KICBpZighKHg9ZFtuXSkmJmQuYWxsKSB4PWQuYWxsW25dOyBmb3IgKGk9MDsheCYmaTxkLmZvcm1zLmxlbmd0aDtpKyspIHg9ZC5mb3Jtc1tpXVtuXTsNCiAgZm9yKGk9MDsheCYmZC5sYXllcnMmJmk8ZC5sYXllcnMubGVuZ3RoO2krKykgeD1NTV9maW5kT2JqKG4sZC5sYXllcnNbaV0uZG9jdW1lbnQpOw0KICBpZigheCAmJiBkLmdldEVsZW1lbnRCeUlkKSB4PWQuZ2V0RWxlbWVudEJ5SWQobik7IHJldHVybiB4Ow0KfQ0KDQpmdW5jdGlvbiBnZXRIVyh0LGEpIHsNCiAgdmFyIHIscCxoPTAsdz0wO2lmKChwPU1NX2ZpbmRPYmooYSkpICE9bnVsbCl7DQogIGlmKGRvY3VtZW50LmFsbCB8fCBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCl7aD1wYXJzZUludChwLm9mZnNldEhlaWdodCk7dz1wYXJzZUludChwLm9mZnNldFdpZHRoKTsNCiAgaWYoIWgpe2g9cGFyc2VJbnQocC5zdHlsZS5waXhlbEhlaWdodCk7dz1wYXJzZUludChwLnN0eWxlLnBpeGVsV2lkdGgpO30NCiAgfWVsc2UgaWYoZG9jdW1lbnQubGF5ZXJzKXtoPXBhcnNlSW50KHAuY2xpcC5oZWlnaHQpO3c9cGFyc2VJbnQocC5jbGlwLndpZHRoKTt9fQ0KICBpZih0PT0id2lkdGgiKXtyPXc7fWVsc2V7cj1oO31yZXR1cm4gcjsgDQp9DQoNCmZ1bmN0aW9uIE1NMWR3dCgpIHsNCiAgdmFyIGcsbGgsc3csZnIgPSBmYWxzZTsNCiAgaWYoIWRvY3VtZW50Lm1jKXJldHVybjsNCiAgZm9yKHZhciB4PTA7eDxtMS5sZW5ndGg7eCsrKXt0bD1tMVt4XS5pZDtsaD0iUDdDTTFEV1QwIit0bDsNCglpZigoZz1NTV9maW5kT2JqKGxoKSkgIT1udWxsKXtmcj10cnVlO3N3PTA7YnJlYWs7fQ0KCWxoPSJQN0NNMURXVDEiK3RsO2lmKChnPU1NX2ZpbmRPYmoobGgpKSAhPW51bGwpe2ZyPXRydWU7c3c9MTticmVhazt9fQ0KICBpZihmcil7ZXZhbCgidHJpZ01lbnVNYWdpYzEoJyIrdGwrIicsIitzdysiKSIpO30NCn0NCg0KZnVuY3Rpb24gc2V0TWVudU1hZ2ljMSgpIHsNCiAgdmFyIHMsZCxnLGcyLGdnLHd3LGt4LHRoLHR1LHRzLG51LHh4LGs9MCxwYT0wO2FyZ3M9c2V0TWVudU1hZ2ljMS5hcmd1bWVudHM7DQogIGlmKChwYXJzZUludChuYXZpZ2F0b3IuYXBwVmVyc2lvbik+NCB8fCBuYXZpZ2F0b3IudXNlckFnZW50LmluZGV4T2YoIk1TSUUiKT4tMSkmJiBuYXZpZ2F0b3IudXNlckFnZW50LmluZGV4T2YoIk9wZXJhIik9PS0xKXtwYT0icHgiO30NCiAgaWYobmF2aWdhdG9yLnVzZXJBZ2VudC5pbmRleE9mKCJPcGVyYSIpPi0xKXtQN09wZXJhVz13aW5kb3cuaW5uZXJXaWR0aDtQN09wZXJhSD13aW5kb3cuaW5uZXJIZWlnaHQ7fQ0KICBpZighZG9jdW1lbnQubWMpIHsgbTM9bmV3IEFycmF5KCk7DQogICBtPW5ldyBBcnJheSgpO2RvY3VtZW50Lm1jPXRydWU7bXM9bmV3IEFycmF5KCk7ZG9jdW1lbnQuaW1zd2FwPW5ldyBBcnJheSgpO2RvY3VtZW50Lmltc3dhcG89bmV3IEFycmF5KCk7DQogICBtMT1uZXcgQXJyYXkoKTttMj1uZXcgQXJyYXkoKTttcHJvcD1uZXcgT2JqZWN0KCk7bXByb3Aub2Zmc2V0PWFyZ3NbMF07bXByb3AucmF0ZT1hcmdzWzFdOw0KICAgbXByb3AuZGVsYXk9YXJnc1syXTttcHJvcC5ib3R0b209YXJnc1szXTsNCiAgIGlmKGRvY3VtZW50LmxheWVycyl7bXByb3AucGFnZWggPSBkb2N1bWVudC5oZWlnaHQ7fX0NCiAgZm9yKHZhciB4PTQ7eDxhcmdzLmxlbmd0aDt4Kz0zKXtpZigoZz1NTV9maW5kT2JqKGFyZ3NbeF0pKSAhPW51bGwpew0KICAgIG1ba109YXJnc1t4XTtnLmltbmFtZT1hcmdzW3grMl07Zy5zdWI9YXJnc1t4KzFdO20zW2tdPTA7DQogICAgZzI9TU1fZmluZE9iaihhcmdzW3grMl0pO3R1PWcyLnNyYzt0cz10dS5sYXN0SW5kZXhPZigiLiIpOw0KICAgIG51PXR1LnN1YnN0cmluZygwLHRzKSsiX29wZW4iK3R1LnN1YnN0cmluZyh0cyx0dS5sZW5ndGgpOw0KCW51Mj10dS5zdWJzdHJpbmcoMCx0cykrIl9vdmVyIit0dS5zdWJzdHJpbmcodHMsdHUubGVuZ3RoKTsNCiAgICBkb2N1bWVudC5pbXN3YXBba109bmV3IEltYWdlKCk7ZG9jdW1lbnQuaW1zd2FwW2tdLnNyYz10dTsNCglkb2N1bWVudC5pbXN3YXBvW2tdPW5ldyBJbWFnZSgpO2RvY3VtZW50Lmltc3dhcG9ba10uc3JjPXR1O2srKzt9fQ0KICB2YXIgbGY9MDtmb3IgKHZhciBqPTA7ajxtLmxlbmd0aDtqKyspew0KICAgaWYoKGc9TU1fZmluZE9iaihtW2pdKSkgIT1udWxsKXtkPShkb2N1bWVudC5sYXllcnMpP2c6Zy5zdHlsZTttMVtqXT1nO2cud2FpdGluZz1mYWxzZTsNCiAgICBpZihqPT0wKXtsZj1wYXJzZUludChkLmxlZnQpO3RoPXBhcnNlSW50KGQudG9wKTt9DQogICAgaWYoaj4wKXtkLmxlZnQ9KGxmK3BhKTt0aCs9Z2V0SFcoJ2hlaWdodCcsbVtqLTFdKTtkLnRvcD0odGgrcGEpO30NCiAgICBpZigocz1NTV9maW5kT2JqKGcuc3ViKSkgIT1udWxsKXttMltqXT1zO3d3PWdldEhXKCd3aWR0aCcsZy5zdWIpOw0KICAgICBreD1sZi13dy0zMDtkZD0oZG9jdW1lbnQubGF5ZXJzKT9zOnMuc3R5bGU7DQogICAgIGRkLmxlZnQ9KGt4K3BhKTtkZC50b3A9KHRoK3BhKTttc1tqXT10aDtkZC52aXNpYmlsaXR5PSJ2aXNpYmxlIjtzLm9wZW49ZmFsc2U7cy53YWl0aW5nPWZhbHNlO319fQ0KICBpZigoZz1NTV9maW5kT2JqKG1wcm9wLmJvdHRvbSkpICE9bnVsbCl7ZD0oZG9jdW1lbnQubGF5ZXJzKT9nOmcuc3R5bGU7DQogICBkLmxlZnQ9KGxmK3BhcnNlSW50KGFyZ3NbMF0pK3BhKTt0aCs9Z2V0SFcoJ2hlaWdodCcsbVttLmxlbmd0aC0xXSk7ZC50b3A9KHRoK3BhKTt9DQp9DQoNCmZ1bmN0aW9uIEJNMShlbCx4LHksYSxiLGMscykgew0KIHZhciBnLGVsbz1lbCxmPSIiLG09ZmFsc2UsZD0iIjt4PXBhcnNlSW50KHgpO3k9cGFyc2VJbnQoeSk7DQogdmFyIHQgPSAnZy5CTSA9IHNldFRpbWVvdXQoIkJNMShcJycrZWxvKydcJywnOyANCiBpZiAoKGc9TU1fZmluZE9iaihlbCkpIT1udWxsKSB7ZD0oZG9jdW1lbnQubGF5ZXJzKT9nOmcuc3R5bGU7fWVsc2V7cmV0dXJuO30NCiB2YXIgeHg9KHBhcnNlSW50KGQubGVmdCkpP3BhcnNlSW50KGQubGVmdCk6MDsNCiB2YXIgeXk9KHBhcnNlSW50KGQudG9wKSk/cGFyc2VJbnQoZC50b3ApOjA7DQogdmFyIGk9cGFyc2VJbnQoYSk7DQogIGlmIChldmFsKGcubW92ZWQpKXtjbGVhclRpbWVvdXQoZy5CTSk7fQ0KICBpZiAoeHg8eCl7eHgrPWk7bT10cnVlO2lmKHh4Pngpe3h4PXg7fX0NCiAgaWYgKHh4Pngpe3h4LT1pO209dHJ1ZTtpZih4eDx4KXt4eD14O319DQogIGlmICh5eTx5KXt5eSs9aTttPXRydWU7aWYoeXk+eSl7eXk9eTt9fQ0KICBpZiAoeXk+eSl7eXktPWk7bT10cnVlO2lmKHl5PHkpe3l5PXk7fX0NCiBpZiAobSkgew0KICBpZigocGFyc2VJbnQobmF2aWdhdG9yLmFwcFZlcnNpb24pPjQgfHwgbmF2aWdhdG9yLnVzZXJBZ2VudC5pbmRleE9mKCJNU0lFIik+LTEpJiYgbmF2aWdhdG9yLnVzZXJBZ2VudC5pbmRleE9mKCJPcGVyYSIpPT0tMSl7ICAgDQogICB4eCs9InB4Ijt5eSs9InB4Ijt9ZC5sZWZ0PXh4O2QudG9wPXl5O2cubW92ZWQ9dHJ1ZTtldmFsKHQreCsnLCcreSsnLCcrYSsnLCcrYisnLCcrYysnLDApIiwnK2IrJyknKTsNCiAgfWVsc2Uge2cubW92ZWQ9ZmFsc2U7d2FpdChlbG8pO30NCn0NCg0KZnVuY3Rpb24gd2FpdChhKSB7DQogIHZhciBtYSxtYjtpZigobWI9TU1fZmluZE9iaihhKSkgIT1udWxsKXsNCiAgIGlmKCFtYi53YWl0aW5nIHx8IG1iLndhaXRpbmc9PSJub25lIil7cmV0dXJuO30NCiAgICBtYT1tYi53YWl0aW5nO21iLndhaXRpbmc9ZmFsc2U7ZXZhbChtYSk7fQ0KfQ0KDQpmdW5jdGlvbiB0cmlnTWVudU1hZ2ljMShhLHN3KSB7DQogIHZhciB4LGcsZ2csZCxkZCx3LGxwLHRwLGltLGltMix0cyxudSxlLHBhPTA7aWYoIWRvY3VtZW50Lm1jKXJldHVybjsNCiAgaWYoKHBhcnNlSW50KG5hdmlnYXRvci5hcHBWZXJzaW9uKT40IHx8IG5hdmlnYXRvci51c2VyQWdlbnQuaW5kZXhPZigiTVNJRSIpPi0xKSYmIG5hdmlnYXRvci51c2VyQWdlbnQuaW5kZXhPZigiT3BlcmEiKT09LTEpe3BhPSJweCI7fQ0KICBpZihuYXZpZ2F0b3IudXNlckFnZW50LmluZGV4T2YoIk9wZXJhIik+LTEpe2lmKCBQN09wZXJhVyE9d2luZG93LmlubmVyV2lkdGggfHwgUDdPcGVyYUghPXdpbmRvdy5pbm5lckhlaWdodClzZXRNZW51TWFnaWMxKCk7fQ0KICB2YXIgb2ZzPXBhcnNlSW50KG1wcm9wLm9mZnNldCksdHJ0ID0gcGFyc2VJbnQobXByb3AucmF0ZSk7DQogIHZhciB0ZHk9cGFyc2VJbnQobXByb3AuZGVsYXkpLHRzYix0bGYsdHN0O2Zvcih4PTA7eDxtLmxlbmd0aDt4Kyspew0KICBpZihtW3hdPT1hKXtkPW0xW3hdO2RkPShkb2N1bWVudC5sYXllcnMpP2Q6ZC5zdHlsZTtnPW0yW3hdO2dnPShkb2N1bWVudC5sYXllcnMpP2c6Zy5zdHlsZTsNCiAgIGU9TU1fZmluZE9iaihkLmltbmFtZSk7aW09ZS5zcmM7dHM9aW0ucmVwbGFjZSgiX29wZW4iLCIiKTt0cz10cy5yZXBsYWNlKCJfb3ZlciIsIiIpOw0KICAgaWYoIWcub3Blbil7dHN0PSJjbG9zZWQiO2ltMj10cy5sYXN0SW5kZXhPZigiLiIpOw0KICAgbnU9dHMuc3Vic3RyaW5nKDAsaW0yKSsiX29wZW4iK3RzLnN1YnN0cmluZyhpbTIsdHMubGVuZ3RoKTt0cyA9IG51O31lbHNle3RzdD0ib3BlbiJ9YnJlYWs7fX0NCiAgIGlmKGRvY3VtZW50Lm1tMVEpe3RydD0yMDAwMDtkb2N1bWVudC5tbTFRPWZhbHNlO30NCiAgZm9yKGo9MDtqPG0ubGVuZ3RoO2orKyl7DQogICBkPW0xW2pdO2RkPShkb2N1bWVudC5sYXllcnMpP2Q6ZC5zdHlsZTtnPW0yW2pdO2dnPShkb2N1bWVudC5sYXllcnMpP2c6Zy5zdHlsZTsNCiAgIGlmKGo9PTApe3RsZj1wYXJzZUludChkZC5sZWZ0KTt9aWYoZy5vcGVuKXsNCiAgIHc9Z2V0SFcoJ3dpZHRoJyxkLnN1YikrMzA7dy09cGFyc2VJbnQoZGQubGVmdCk7dyo9LTE7ZC53YWl0aW5nPWZhbHNlOw0KICAgZXZhbCgiQk0xKCciK2Quc3ViKyInLCIrdysiLCIrcGFyc2VJbnQoZ2cudG9wKSsiLCIrMjAwMDArIiwiK3RkeSsiLDAsMCkiKTt9DQogICBkLndhaXRpbmc9ZmFsc2U7Zy5vcGVuPWZhbHNlOw0KICAgaWYocGFyc2VJbnQoc3cpPT0xKXtlPU1NX2ZpbmRPYmooZC5pbW5hbWUpO2ltPWUuc3JjO2ltMj1pbS5yZXBsYWNlKCJfb3BlbiIsIiIpO2Uuc3JjPWltMjt9fQ0KICB2YXIgdG50PW5ldyBBcnJheSgpO3ZhciBkZj0wLHRjZD0wLHRkbD1tWzBdO2ZvcihqPTA7ajxtLmxlbmd0aDtqKyspew0KICBkPW0xW2pdO2RkPShkb2N1bWVudC5sYXllcnMpP2Q6ZC5zdHlsZTtnPW0yW2pdO2dnPShkb2N1bWVudC5sYXllcnMpP2c6Zy5zdHlsZTsNCiAgaWYoaj09MCl7dGg9cGFyc2VJbnQoZGQudG9wKTt9dG50W2pdPXRoO2RmPU1hdGguYWJzKHBhcnNlSW50KGRkLnRvcCktdGgpOw0KICBpZihkZj50Y2Qpe3RkbD1tW2pdO3RjZD1kZjt9dGgrPWdldEhXKCdoZWlnaHQnLG1bal0pOw0KICBpZih4PT1qICYmIHRzdD09ImNsb3NlZCIpe3RzYj10aDtpZihtM1tqXSE9MSl7dGgrPWdldEhXKCdoZWlnaHQnLGQuc3ViKTt9fW1zW2pdPXRoO30NCiAgaWYodHN0PT0iY2xvc2VkIil7ZD1tMVt4XTtkZD0oZG9jdW1lbnQubGF5ZXJzKT9kOmQuc3R5bGU7DQogICBnPW0yW3hdO2dnPShkb2N1bWVudC5sYXllcnMpP2c6Zy5zdHlsZTtscD10bGYrb2ZzOw0KICAgZ2cudG9wPSh0c2IrcGEpO21zW3hdPXRzYjtlPU1NX2ZpbmRPYmooZC5pbW5hbWUpO2lmKHBhcnNlSW50KHN3KT09MSl7ZS5zcmM9dHM7fQ0KICAgZy5vcGVuPXRydWU7aWYobTNbeF0hPTEpe2dnLnZpc2liaWxpdHk9InZpc2libGUiO3ZhciByO3I9TU1fZmluZE9iaih0ZGwpOwkJDQogICByLndhaXRpbmc9IkJNMSgnIitkLnN1YisiJywiK2xwKyIsIit0c2IrIiwiKzIwMDAwKyIsIit0ZHkrIiwwLDApIiA7fQ0KICAgfWVsc2V7ZD1tMVttMS5sZW5ndGgtMV07ZC53YWl0aW5nPSJub25lIjt9DQogIGZvcihqPTA7ajxtLmxlbmd0aDtqKysgKXtldmFsKCJCTTEoJyIrbVtqXSsiJywiK3RsZisiLCIrdG50W2pdKyIsIit0cnQrIiwiK3RkeSsiLDAsMCkiKTt9DQogIGlmKChnPU1NX2ZpbmRPYmoobXByb3AuYm90dG9tKSkgIT1udWxsKXtkPShkb2N1bWVudC5sYXllcnMpP2c6Zy5zdHlsZTtnLndhaXRpbmc9ZmFsc2U7DQogICBldmFsKCJCTTEoJyIrbXByb3AuYm90dG9tKyInLCIrKHRsZitvZnMpKyIsIit0aCsiLCIrdHJ0KyIsIit0ZHkrIiwwLDApIik7DQogICB0aCs9KGRvY3VtZW50LmxheWVycyk/Z2V0SFcoJ2hlaWdodCcsbXByb3AuYm90dG9tKTowO30NCiAgaWYoZG9jdW1lbnQubGF5ZXJzKXt2YXIgdHcyPWRvY3VtZW50LndpZHRoOw0KICAgIGlmKGRvY3VtZW50LmhlaWdodDx0aCkge2RvY3VtZW50LmhlaWdodD10aDtkb2N1bWVudC53aWR0aD10dzI7fX0NCn0NCg0KZnVuY3Rpb24gcm9sbENNZW51MShldixhLGIpIHsNCiB2YXIgZSxpbSx0cyxqLG51LGcseCx0ZXY9ZXYudHlwZTsNCiBpZighZG9jdW1lbnQubWMpcmV0dXJuOw0KIGlmKHRldj09Im1vdXNlb3ZlciIpe2Zvcih4PTA7eDxtLmxlbmd0aDt4Kyspew0KIGlmKG1beF09PWEpe2c9bTJbeF07aWYocGFyc2VJbnQoYik9PTAgJiYgZy5vcGVuKSB7YnJlYWs7cmV0dXJuO30NCiBlPU1NX2ZpbmRPYmoobTFbeF0uaW1uYW1lKTtpbT1lLnNyYzt0cz1pbS5yZXBsYWNlKCJfb3BlbiIsIiIpOw0KIHRzPXRzLnJlcGxhY2UoIl9vdmVyIiwiIik7aj10cy5sYXN0SW5kZXhPZigiLiIpOw0KIGUuc3JjPXRzLnN1YnN0cmluZygwLGopKyJfb3ZlciIrdHMuc3Vic3RyaW5nKGosdHMubGVuZ3RoKTticmVhazt9fQ0KIH1lbHNlIGlmKHRldj09Im1vdXNlb3V0Iil7Zm9yKHg9MDt4PG0ubGVuZ3RoO3grKyl7DQogaWYobVt4XT09YSl7ZT1NTV9maW5kT2JqKGQ9bTFbeF0uaW1uYW1lKTtpbT1lLnNyYzsNCiBnPW0yW3hdO3RzPWltLnJlcGxhY2UoIl9vcGVuIiwiIik7dHM9dHMucmVwbGFjZSgiX292ZXIiLCIiKTsNCiBpZihnLm9wZW4pe2o9dHMubGFzdEluZGV4T2YoIi4iKTsNCiBudT10cy5zdWJzdHJpbmcoMCxqKSsiX29wZW4iK3RzLnN1YnN0cmluZyhqLHRzLmxlbmd0aCk7DQogfWVsc2V7bnU9dHM7fWUuc3JjPW51O2JyZWFrO319fQ0KfQ0KDQpmdW5jdGlvbiB0cmlnTU0xdXJsKHBhcmFtLG9wdCl7DQogIHZhciB1cix4LGksbnYsbW4scHI9bmV3IEFycmF5KCk7DQogIHVyPWRvY3VtZW50LlVSTDt4PXVyLmluZGV4T2YoIj8iKTsNCiAgaWYoeD4xKXtwcj11ci5zdWJzdHJpbmcoeCsxLHVyLmxlbmd0aCkuc3BsaXQoIiYiKTsNCiAgZm9yKGk9MDtpPHByLmxlbmd0aDtpKyspe252PXByW2ldLnNwbGl0KCI9Iik7DQogIGlmKG52Lmxlbmd0aD4wKXtpZih1bmVzY2FwZShudlswXSk9PXBhcmFtKXsNCiAgbW49Im1lbnUiK3VuZXNjYXBlKG52WzFdKTsNCiAgZXZhbCgidHJpZ01lbnVNYWdpYzEoJyIrbW4rIicsIitvcHQrIikiKTt9fX19DQogIH0NCiAgDQogIGRvY3VtZW50Lm1tMVE9dHJ1ZTs=]]></response>
      <responseRedirected>false</responseRedirected>
    </requestresponse>
  </issue>
  <issue>
    <serialNumber>1719400533041398784</serialNumber>
    <type>5244416</type>
    <name>Cookie without HttpOnly flag set</name>
    <host ip="192.168.216.139">http://192.168.216.139:8080</host>
    <path><![CDATA[/WebGoat/attack]]></path>
    <location><![CDATA[/WebGoat/attack]]></location>
    <severity>Low</severity>
    <confidence>Firm</confidence>
    <issueBackground><![CDATA[If the HttpOnly attribute is set on a cookie, then the cookie's value cannot be read or set by client-side JavaScript. This measure can prevent certain client-side attacks, such as cross-site scripting, from trivially capturing the cookie's value via an injected script.]]></issueBackground>
    <remediationBackground><![CDATA[There is usually no good reason not to set the HttpOnly flag on all cookies. Unless you specifically require legitimate client-side scripts within your application to read or set a cookie's value, you should set the HttpOnly flag by including this attribute within the relevant Set-cookie directive.<br><br>You should be aware that the restrictions imposed by the HttpOnly flag can potentially be circumvented in some circumstances, and that numerous other serious attacks can be delivered by client-side script injection, aside from simple cookie stealing.]]></remediationBackground>
    <issueDetail><![CDATA[The following cookie was issued by the application and does not have the HttpOnly flag set:<ul><li><b>JSESSIONID=1115D46CB13A097B975996BF90C21455; Path=/WebGoat</b></li></ul>The cookie appears to contain a session token, which may increase the risk associated with this issue. You should review the contents of the cookie to determine its function.]]></issueDetail>
    <issueDetailItems>
      <issueDetailItem><![CDATA[JSESSIONID=1115D46CB13A097B975996BF90C21455; Path=/WebGoat]]></issueDetailItem>
    </issueDetailItems>
    <requestresponse>
      <request method="GET" base64="true"><![CDATA[R0VUIC9XZWJHb2F0L2F0dGFjayBIVFRQLzEuMQ0KQWNjZXB0OiB0ZXh0L2h0bWwsIGFwcGxpY2F0aW9uL3hodG1sK3htbCwgKi8qDQpBY2NlcHQtTGFuZ3VhZ2U6IGVuLVVTDQpVc2VyLUFnZW50OiBNb3ppbGxhLzUuMCAoV2luZG93cyBOVCA2LjM7IFdPVzY0OyBUcmlkZW50LzcuMDsgcnY6MTEuMCkgbGlrZSBHZWNrbw0KQWNjZXB0LUVuY29kaW5nOiBnemlwLCBkZWZsYXRlDQpIb3N0OiAxOTIuMTY4LjIxNi4xMzk6ODA4MA0KQXV0aG9yaXphdGlvbjogQmFzaWMgWjNWbGMzUTZaM1ZsYzNRPQ0KUHJveHktQ29ubmVjdGlvbjogS2VlcC1BbGl2ZQ0KRE5UOiAxDQoNCg==]]></request>
      <response base64="true"><![CDATA[SFRUUC8xLjEgMjAwIE9LDQpTZXJ2ZXI6IEFwYWNoZS1Db3lvdGUvMS4xDQpQcmFnbWE6IE5vLWNhY2hlDQpDYWNoZS1Db250cm9sOiBuby1jYWNoZQ0KRXhwaXJlczogV2VkLCAzMSBEZWMgMTk2OSAxOTowMDowMCBFU1QNClNldC1Db29raWU6IEpTRVNTSU9OSUQ9MTExNUQ0NkNCMTNBMDk3Qjk3NTk5NkJGOTBDMjE0NTU7IFBhdGg9L1dlYkdvYXQNCkNvbnRlbnQtVHlwZTogdGV4dC9odG1sO2NoYXJzZXQ9SVNPLTg4NTktMQ0KQ29udGVudC1MZW5ndGg6IDM5MzENCkRhdGU6IFRodSwgMTYgT2N0IDIwMTQgMTg6MDQ6MjQgR01UDQoNCg0KDQoNCg0KPCFET0NUWVBFIGh0bWwgUFVCTElDICItLy9XM0MvL0RURCBYSFRNTCAxLjAgVHJhbnNpdGlvbmFsLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL1RSL3hodG1sMS9EVEQveGh0bWwxLXRyYW5zaXRpb25hbC5kdGQiPg0KPGh0bWwgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGh0bWwiPg0KPGhlYWQ+DQo8bWV0YSBodHRwLWVxdWl2PSJDb250ZW50LVR5cGUiIGNvbnRlbnQ9InRleHQvaHRtbDsgY2hhcnNldD1JU08tODg1OS0xIiAvPg0KPHRpdGxlPldlYkdvYXQgVjUuNDwvdGl0bGU+DQo8bGluayByZWw9InN0eWxlc2hlZXQiIGhyZWY9ImNzcy93ZWJnb2F0LmNzcyIgdHlwZT0idGV4dC9jc3MiIC8+DQo8L2hlYWQ+DQoNCjxib2R5Pg0KDQo8ZGl2IGlkPSJ3cmFwIj4NCjxkaXYgaWQ9InRvcCI+PC9kaXY+DQo8ZGl2IGlkPSJzdGFydCI+DQo8cD5UaGFuayB5b3UgZm9yIHVzaW5nIFdlYkdvYXQhIFRoaXMgcHJvZ3JhbSBpcyBhIGRlbW9uc3RyYXRpb24gb2YgY29tbW9uIHdlYiBhcHBsaWNhdGlvbiBmbGF3cy4NClRoZSBleGVyY2lzZXMgYXJlIGludGVuZGVkIHRvIHByb3ZpZGUgaGFuZHMgb24gZXhwZXJpZW5jZSB3aXRoDQphcHBsaWNhdGlvbiBwZW5ldHJhdGlvbiB0ZXN0aW5nIHRlY2huaXF1ZXMuIDwvcD4NCjxwPlRoZSBXZWJHb2F0IHByb2plY3QgaXMgbGVkDQpieSBCcnVjZSBNYXloZXcuIFBsZWFzZSBzZW5kIGFsbCBjb21tZW50cyB0byBCcnVjZSBhdCBXZWJHb2F0QG93YXNwLm9yZy48L3A+DQoNCjxkaXYgaWQ9InRlYW0iPg0KPHRhYmxlIGJvcmRlcj0iMCIgYWxpZ249ImNlbnRlciIgY2xhc3M9Imxlc3NvblRleHQiPg0KCTx0cj4NCgkJPHRkIHdpZHRoPSI1MCUiPg0KCQk8ZGl2IGFsaWduPSJjZW50ZXIiPjxhIGhyZWY9Imh0dHA6Ly93d3cub3dhc3Aub3JnIj48aW1nDQoJCQlib3JkZXI9IjAiIHNyYz0iaW1hZ2VzL2xvZ29zL293YXNwLmpwZyIgYWx0PSJPV0FTUCBGb3VuZGF0aW9uIg0KCQkJbG9uZ2Rlc2M9Imh0dHA6Ly93d3cub3dhc3Aub3JnIiAvPjwvYT48L2Rpdj4NCgkJPC90ZD4NCgkJPHRkIHdpZHRoPSI1MCUiPg0KCQk8ZGl2IGFsaWduPSJjZW50ZXIiPjxhIGhyZWY9Imh0dHA6Ly93d3cuYXNwZWN0c2VjdXJpdHkuY29tIj48aW1nDQoJCQlib3JkZXI9IjAiIHNyYz0iaW1hZ2VzL2xvZ29zL2FzcGVjdC5qcGciIGFsdD0iQXNwZWN0IFNlY3VyaXR5Ig0KCQkJbG9uZ2Rlc2M9Imh0dHA6Ly93d3cuYXNwZWN0c2VjdXJpdHkuY29tIiAvPjwvYT48L2Rpdj4NCgkJPC90ZD4NCgk8L3RyPg0KCTx0cj4NCgkJPHRkIHdpZHRoPSI1MCUiPg0KCQk8ZGl2IGFsaWduPSJjZW50ZXIiPjxzcGFuIGNsYXNzPSJzdHlsZTEiPjxiciAvPg0KCQlXZWJHb2F0IERlc2lnbiBUZWFtIDwvc3Bhbj48L2Rpdj4NCgkJPC90ZD4NCgkJPHRkIHdpZHRoPSI1MCUiPg0KCQk8ZGl2IGFsaWduPSJjZW50ZXIiPjxzcGFuIGNsYXNzPSJzdHlsZTEiPjxiciAvPg0KCQlWNS4zIExlc3NvbiBDb250cmlidXRlcnMgPC9zcGFuPjwvZGl2Pg0KCQk8L3RkPg0KCTwvdHI+DQoJPHRyPg0KCQk8dGQgdmFsaWduPSJ0b3AiPg0KCQk8ZGl2IGFsaWduPSJjZW50ZXIiIGNsYXNzPSJzdHlsZTIiPkJydWNlIE1heWhldzwvZGl2Pg0KCQk8ZGl2IGFsaWduPSJjZW50ZXIiIGNsYXNzPSJzdHlsZTIiPkRhdmlkIEFuZGVyc29uPC9kaXY+DQoJCTxkaXYgYWxpZ249ImNlbnRlciIgY2xhc3M9InN0eWxlMiI+Um9nYW4gRGF3ZXM8L2Rpdj4NCgkJPGRpdiBhbGlnbj0iY2VudGVyIiBjbGFzcz0ic3R5bGUyIj5MYXVyZW5jZSBDYXNleSAoR3JhcGhpY3MpPC9kaXY+DQoJCTxkaXYgYWxpZ249ImNlbnRlciIgY2xhc3M9InN0eWxlMiI+QnJpYW4gQ2lvbWVpPC9kaXY+DQoJCTwvdGQ+DQoJCTx0ZCB2YWxpZ249InRvcCI+DQoJCTxkaXYgYWxpZ249ImNlbnRlciIgY2xhc3M9InN0eWxlMiI+Q2h1Y2sgV2lsbGlzPC9kaXY+DQoJCTxkaXYgYWxpZ249ImNlbnRlciIgY2xhc3M9InN0eWxlMiI+Q2FtIE1vcnJpczwvZGl2Pg0KCQk8ZGl2IGFsaWduPSJjZW50ZXIiIGNsYXNzPSJzdHlsZTIiPllpYW5uaXMgUGF2bG9zb2dsb3U8L2Rpdj4NCgkJPGRpdiBhbGlnbj0iY2VudGVyIiBjbGFzcz0ic3R5bGUyIj48L2Rpdj4NCg0KCQk8L3RkPg0KCTwvdHI+DQoJPHRyPg0KCQk8dGQgaGVpZ2h0PSIyNSIgdmFsaWduPSJib3R0b20iPg0KCQk8ZGl2IGFsaWduPSJjZW50ZXIiPjxzcGFuIGNsYXNzPSJzdHlsZTEiPlNwZWNpYWwgVGhhbmtzDQoJCWZvciBWNS4zPC9zcGFuPjwvZGl2Pg0KCQk8L3RkPg0KCQk8dGQgaGVpZ2h0PSIyNSIgdmFsaWduPSJib3R0b20iPg0KCQk8ZGl2IGFsaWduPSJjZW50ZXIiPjxzcGFuIGNsYXNzPSJzdHlsZTEiPkRvY3VtZW50YXRpb24NCgkJQ29udHJpYnV0ZXJzPC9zcGFuPjwvZGl2Pg0KCQk8L3RkPg0KCTwvdHI+DQoJPHRyPg0KCQk8dGQ+DQoJCTxkaXYgYWxpZ249ImNlbnRlciIgY2xhc3M9InN0eWxlMiI+Q2hyaXN0aW5lIChNYXZlbik8L2Rpdj4NCgkJPGRpdiBhbGlnbj0iY2VudGVyIiBjbGFzcz0ic3R5bGUyIj5NYXJlayBKYXd1cmVrIChJbnRlcm5hdGlvbmFsaXphdGlvbik8L2Rpdj4NCgkJPGJyLz48ZGl2IGFsaWduPSJjZW50ZXIiIGNsYXNzPSJzdHlsZTIiPlRvIGFsbCB3aG8gaGF2ZSBzZW50IGNvbW1lbnRzPC9kaXY+DQoJCQ0KCQk8L3RkPg0KCQk8dGQ+DQoJCTxkaXYgYWxpZ249ImNlbnRlciIgY2xhc3M9InN0eWxlMiI+U2hlcmlmIEtvdXNzYTxiciAvPg0KCQkJKGh0dHA6Ly93d3cuc29mdHdhcmVzZWN1cmVkLmNvbSkNCgkJPC9kaXY+DQoJCTxkaXYgYWxpZ249ImNlbnRlciIgY2xhc3M9InN0eWxlMiI+QXVuZyBLaGFudDxiciAvPg0KCQkoaHR0cDovL3llaGcub3JnLyk8L2Rpdj4NCgkJPGRpdiBhbGlnbj0iY2VudGVyIiBjbGFzcz0ic3R5bGUyIj5FcndpbiBHZWlybmFlcnQ8YnIgLz4NCgkJKGh0dHA6Ly93d3cuemlvbnNlY3VyaXR5LmNvbS8pPC9kaXY+DQoJCTwvdGQ+DQoJPC90cj4NCgk8dHI+DQoJCTx0ZCBjb2xzcGFuPSIyIj4NCgkJPGRpdiBhbGlnbj0iY2VudGVyIiBjbGFzcz0ic3R5bGUyIj4NCgkJPGZvcm0gaWQ9ImZvcm0iIG5hbWU9ImZvcm0iIG1ldGhvZD0icG9zdCIgYWN0aW9uPSJhdHRhY2siPjxpbnB1dA0KCQkJdHlwZT0ic3VibWl0IiBuYW1lPSJzdGFydCIgdmFsdWU9IlN0YXJ0IFdlYkdvYXQiIC8+PC9mb3JtPg0KCQk8L2Rpdj4NCgkJPC90ZD4NCgk8L3RyPg0KCTx0cj4NCgkJPHRkPg0KCQk8ZGl2IGFsaWduPSJjZW50ZXIiIGNsYXNzPSJzdHlsZTIiPiZuYnNwOzwvZGl2Pg0KCQk8L3RkPg0KCTwvdHI+DQo8L3RhYmxlPg0KPC9kaXY+DQo8L2Rpdj4NCjxkaXYgYWxpZ249ImNlbnRlciIgY2xhc3M9InN0eWxlMiI+Jm5ic3A7PC9kaXY+DQo8ZGl2IGFsaWduPSJjZW50ZXIiIGNsYXNzPSJzdHlsZTIiPiZuYnNwOzwvZGl2Pg0KPGRpdiBhbGlnbj0iY2VudGVyIiBjbGFzcz0ic3R5bGUyIj4mbmJzcDs8L2Rpdj4NCjxkaXYgaWQ9Indhcm5pbmciPldBUk5JTkc8YnIgLz4NCldoaWxlIHJ1bm5pbmcgdGhpcyBwcm9ncmFtLCB5b3VyIG1hY2hpbmUgaXMgZXh0cmVtZWx5IHZ1bG5lcmFibGUgdG8NCmF0dGFjayBpZiB5b3UgYXJlIG5vdCBydW5uaW5nIG9uIGxvY2FsaG9zdC4gSWYgdG91IGFyZSBOT1QgcnVubmluZyBvbiBsb2NhbGhvc3QgKGRlZmF1bHQgY29uZmlndXJhdGlvbiksIFlvdSBzaG91bGQgZGlzY29ubmVjdCBmcm9tIHRoZSBuZXR3b3JrIHdoaWxlIHVzaW5nIHRoaXMgcHJvZ3JhbS4NCjxiciAvPg0KPGJyIC8+DQpUaGlzIHByb2dyYW0gaXMgZm9yIGVkdWNhdGlvbmFsIHB1cnBvc2VzIG9ubHkuIFVzZSBvZiB0aGVzZSB0ZWNobmlxdWVzDQp3aXRob3V0IHBlcm1pc3Npb24gY291bGQgbGVhZCB0byBqb2IgdGVybWluYXRpb24sIGZpbmFuY2lhbCBsaWFiaWxpdHksDQphbmQvb3IgY3JpbWluYWwgcGVuYWx0aWVzLjwvZGl2Pg0KPC9kaXY+DQo8L2JvZHk+DQo8L2h0bWw+DQo=]]></response>
      <responseRedirected>false</responseRedirected>
    </requestresponse>
  </issue>
  <issue>
    <serialNumber>7032298447626209280</serialNumber>
    <type>4194576</type>
    <name>X-Forwarded-For dependent response</name>
    <host ip="192.168.216.139">http://192.168.216.139:8080</host>
    <path><![CDATA[/WebGoat/attack]]></path>
    <location><![CDATA[/WebGoat/attack]]></location>
    <severity>Information</severity>
    <confidence>Firm</confidence>
    <issueBackground><![CDATA[The application's responses appear to depend systematically on the presence or absence of an X-Forwarded-For header in requests. This behavior does not necessarily constitute a security vulnerability, and you should investigate the nature of and reason for the differential responses to determine whether a vulnerability is present.<br><br>Some applications enforce access controls based on the remote IP address of the connecting client. For example, an application might expose administrative functionality only to clients connecting from the local IP address of the server. In some configurations, the presence of an X-Forwarded-For header misleads the application about the client's IP address, allowing an attacker to masquerade as a trusted user. You should review the purpose of the relevant functionality to determine whether this might be the case.]]></issueBackground>
    <remediationBackground><![CDATA[The X-Forwarded-For header is not a robust foundation on which to build any security measures, such as access controls. Any such measures should be replaced with more secure alternatives that are not vulnerable to spoofing.<br><br>If the platform application server returns incorrect information about the client's IP address due to the presence of an X-Forwarded-For header, then the server may need to be reconfigured, or an alternative method of identifying clients should be used.]]></remediationBackground>
    <requestresponse>
      <request method="GET" base64="true"><![CDATA[R0VUIC9XZWJHb2F0L2F0dGFjaz9TY3JlZW49ODkxNjI0NjQ2Jm1lbnU9NSBIVFRQLzEuMQ0KSG9zdDogMTkyLjE2OC4yMTYuMTM5OjgwODANCkFjY2VwdDogKi8qDQpBY2NlcHQtTGFuZ3VhZ2U6IGVuDQpVc2VyLUFnZW50OiBNb3ppbGxhLzUuMCAoY29tcGF0aWJsZTsgTVNJRSA5LjA7IFdpbmRvd3MgTlQgNi4xOyBXaW42NDsgeDY0OyBUcmlkZW50LzUuMCkNCkNvbm5lY3Rpb246IGNsb3NlDQpKU0VTU0lPTklEPTlGMjI1NDMwQjNBMDlGRUIzMEY3MjZCRUMyRkY3NUQwDQoNCg==]]></request>
      <response base64="true"><![CDATA[SFRUUC8xLjEgNDAxIFVuYXV0aG9yaXplZA0KU2VydmVyOiBBcGFjaGUtQ295b3RlLzEuMQ0KUHJhZ21hOiBOby1jYWNoZQ0KQ2FjaGUtQ29udHJvbDogbm8tY2FjaGUNCkV4cGlyZXM6IFdlZCwgMzEgRGVjIDE5NjkgMTk6MDA6MDAgRVNUDQpXV1ctQXV0aGVudGljYXRlOiBCYXNpYyByZWFsbT0iV2ViR29hdCBBcHBsaWNhdGlvbiINCkNvbnRlbnQtVHlwZTogdGV4dC9odG1sO2NoYXJzZXQ9dXRmLTgNCkNvbnRlbnQtTGVuZ3RoOiA5NTQNCkRhdGU6IFRodSwgMTYgT2N0IDIwMTQgMTg6MTk6NDQgR01UDQpDb25uZWN0aW9uOiBjbG9zZQ0KDQo8aHRtbD48aGVhZD48dGl0bGU+QXBhY2hlIFRvbWNhdC82LjAuMzIgLSBFcnJvciByZXBvcnQ8L3RpdGxlPjxzdHlsZT48IS0tSDEge2ZvbnQtZmFtaWx5OlRhaG9tYSxBcmlhbCxzYW5zLXNlcmlmO2NvbG9yOndoaXRlO2JhY2tncm91bmQtY29sb3I6IzUyNUQ3Njtmb250LXNpemU6MjJweDt9IEgyIHtmb250LWZhbWlseTpUYWhvbWEsQXJpYWwsc2Fucy1zZXJpZjtjb2xvcjp3aGl0ZTtiYWNrZ3JvdW5kLWNvbG9yOiM1MjVENzY7Zm9udC1zaXplOjE2cHg7fSBIMyB7Zm9udC1mYW1pbHk6VGFob21hLEFyaWFsLHNhbnMtc2VyaWY7Y29sb3I6d2hpdGU7YmFja2dyb3VuZC1jb2xvcjojNTI1RDc2O2ZvbnQtc2l6ZToxNHB4O30gQk9EWSB7Zm9udC1mYW1pbHk6VGFob21hLEFyaWFsLHNhbnMtc2VyaWY7Y29sb3I6YmxhY2s7YmFja2dyb3VuZC1jb2xvcjp3aGl0ZTt9IEIge2ZvbnQtZmFtaWx5OlRhaG9tYSxBcmlhbCxzYW5zLXNlcmlmO2NvbG9yOndoaXRlO2JhY2tncm91bmQtY29sb3I6IzUyNUQ3Njt9IFAge2ZvbnQtZmFtaWx5OlRhaG9tYSxBcmlhbCxzYW5zLXNlcmlmO2JhY2tncm91bmQ6d2hpdGU7Y29sb3I6YmxhY2s7Zm9udC1zaXplOjEycHg7fUEge2NvbG9yIDogYmxhY2s7fUEubmFtZSB7Y29sb3IgOiBibGFjazt9SFIge2NvbG9yIDogIzUyNUQ3Njt9LS0+PC9zdHlsZT4gPC9oZWFkPjxib2R5PjxoMT5IVFRQIFN0YXR1cyA0MDEgLSA8L2gxPjxIUiBzaXplPSIxIiBub3NoYWRlPSJub3NoYWRlIj48cD48Yj50eXBlPC9iPiBTdGF0dXMgcmVwb3J0PC9wPjxwPjxiPm1lc3NhZ2U8L2I+IDx1PjwvdT48L3A+PHA+PGI+ZGVzY3JpcHRpb248L2I+IDx1PlRoaXMgcmVxdWVzdCByZXF1aXJlcyBIVFRQIGF1dGhlbnRpY2F0aW9uICgpLjwvdT48L3A+PEhSIHNpemU9IjEiIG5vc2hhZGU9Im5vc2hhZGUiPjxoMz5BcGFjaGUgVG9tY2F0LzYuMC4zMjwvaDM+PC9ib2R5PjwvaHRtbD4=]]></response>
      <responseRedirected>false</responseRedirected>
    </requestresponse>
    <requestresponse>
      <request method="GET" base64="true"><![CDATA[R0VUIC9XZWJHb2F0L2F0dGFjaz9TY3JlZW49ODkxNjI0NjQ2Jm1lbnU9NSBIVFRQLzEuMQ0KSG9zdDogMTkyLjE2OC4yMTYuMTM5OjgwODANCkFjY2VwdDogKi8qDQpBY2NlcHQtTGFuZ3VhZ2U6IGVuDQpVc2VyLUFnZW50OiBNb3ppbGxhLzUuMCAoY29tcGF0aWJsZTsgTVNJRSA5LjA7IFdpbmRvd3MgTlQgNi4xOyBXaW42NDsgeDY0OyBUcmlkZW50LzUuMCkNCkNvbm5lY3Rpb246IGNsb3NlDQpKU0VTU0lPTklEPTlGMjI1NDMwQjNBMDlGRUIzMEY3MjZCRUMyRkY3NUQwDQpYLUZvcndhcmRlZC1Gb3I6IDEyNy4wLjAuMQ0KDQo=]]></request>